spring:
  application:
    name: strava-weekly
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  main:
    allow-bean-definition-overriding: true # TODO: Find how to remove this

server:
  error:
    whitelabel:
      enabled: false

security:
  oauth2:
    client:
      # For client id and secret, refer to:
      # https://www.strava.com/settings/api
      # Instead of setting here, see README.md to set as command line arguments
      client-id: ${CLIENT_ID} #SECRET, DO NOT COMMIT TO REPOSITORY
      client-secret: ${CLIENT_SECRET} #SECRET, DO NOT COMMIT TO REPOSITORY
      access-token-uri: https://www.strava.com/oauth/token
      user-authorization-uri: https://www.strava.com/oauth/authorize
      scope: activity:read_all
      token-name: access_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      user-info-uri: https://www.strava.com/api/v3/athlete
